/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  AdminClientsListClients200,
  AdminClientsListClientsParams,
  AdminClientsSetClientStatusBody,
  CreateOAuthClientRequest,
  ErrorResponse,
  OAuthClient,
  UpdateOAuthClientRequest,
} from "../title.schemas";

export const adminClientsListClients = (
  params?: MaybeRef<AdminClientsListClientsParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AdminClientsListClients200>> => {
  params = unref(params);

  return axios.get(`/api/v1/admin/clients`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  });
};

export const getAdminClientsListClientsQueryKey = (
  params?: MaybeRef<AdminClientsListClientsParams>,
) => {
  return ["api", "v1", "admin", "clients", ...(params ? [params] : [])] as const;
};

export const getAdminClientsListClientsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminClientsListClients>>,
  TError = AxiosError<ErrorResponse>,
>(
  params?: MaybeRef<AdminClientsListClientsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminClientsListClients>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getAdminClientsListClientsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminClientsListClients>>> = ({
    signal,
  }) => adminClientsListClients(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminClientsListClients>>,
    TError,
    TData
  >;
};

export type AdminClientsListClientsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminClientsListClients>>
>;
export type AdminClientsListClientsQueryError = AxiosError<ErrorResponse>;

export function useAdminClientsListClients<
  TData = Awaited<ReturnType<typeof adminClientsListClients>>,
  TError = AxiosError<ErrorResponse>,
>(
  params?: MaybeRef<AdminClientsListClientsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminClientsListClients>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminClientsListClientsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const adminClientsCreateClient = (
  createOAuthClientRequest: MaybeRef<CreateOAuthClientRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<OAuthClient>> => {
  createOAuthClientRequest = unref(createOAuthClientRequest);

  return axios.post(`/api/v1/admin/clients`, createOAuthClientRequest, options);
};

export const getAdminClientsCreateClientMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminClientsCreateClient>>,
    TError,
    { data: CreateOAuthClientRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminClientsCreateClient>>,
  TError,
  { data: CreateOAuthClientRequest },
  TContext
> => {
  const mutationKey = ["adminClientsCreateClient"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminClientsCreateClient>>,
    { data: CreateOAuthClientRequest }
  > = (props) => {
    const { data } = props ?? {};

    return adminClientsCreateClient(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminClientsCreateClientMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminClientsCreateClient>>
>;
export type AdminClientsCreateClientMutationBody = CreateOAuthClientRequest;
export type AdminClientsCreateClientMutationError = AxiosError<ErrorResponse>;

export const useAdminClientsCreateClient = <TError = AxiosError<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminClientsCreateClient>>,
      TError,
      { data: CreateOAuthClientRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminClientsCreateClient>>,
  TError,
  { data: CreateOAuthClientRequest },
  TContext
> => {
  const mutationOptions = getAdminClientsCreateClientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminClientsGetClient = (
  clientId: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<OAuthClient>> => {
  clientId = unref(clientId);

  return axios.get(`/api/v1/admin/clients/${clientId}`, options);
};

export const getAdminClientsGetClientQueryKey = (clientId?: MaybeRef<string>) => {
  return ["api", "v1", "admin", "clients", clientId] as const;
};

export const getAdminClientsGetClientQueryOptions = <
  TData = Awaited<ReturnType<typeof adminClientsGetClient>>,
  TError = AxiosError<ErrorResponse>,
>(
  clientId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminClientsGetClient>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getAdminClientsGetClientQueryKey(clientId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof adminClientsGetClient>>> = ({ signal }) =>
    adminClientsGetClient(clientId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(clientId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof adminClientsGetClient>>, TError, TData>;
};

export type AdminClientsGetClientQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminClientsGetClient>>
>;
export type AdminClientsGetClientQueryError = AxiosError<ErrorResponse>;

export function useAdminClientsGetClient<
  TData = Awaited<ReturnType<typeof adminClientsGetClient>>,
  TError = AxiosError<ErrorResponse>,
>(
  clientId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof adminClientsGetClient>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAdminClientsGetClientQueryOptions(clientId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const adminClientsUpdateClient = (
  clientId: MaybeRef<string>,
  updateOAuthClientRequest: MaybeRef<UpdateOAuthClientRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<OAuthClient>> => {
  clientId = unref(clientId);
  updateOAuthClientRequest = unref(updateOAuthClientRequest);

  return axios.patch(`/api/v1/admin/clients/${clientId}`, updateOAuthClientRequest, options);
};

export const getAdminClientsUpdateClientMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminClientsUpdateClient>>,
    TError,
    { clientId: string; data: UpdateOAuthClientRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminClientsUpdateClient>>,
  TError,
  { clientId: string; data: UpdateOAuthClientRequest },
  TContext
> => {
  const mutationKey = ["adminClientsUpdateClient"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminClientsUpdateClient>>,
    { clientId: string; data: UpdateOAuthClientRequest }
  > = (props) => {
    const { clientId, data } = props ?? {};

    return adminClientsUpdateClient(clientId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminClientsUpdateClientMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminClientsUpdateClient>>
>;
export type AdminClientsUpdateClientMutationBody = UpdateOAuthClientRequest;
export type AdminClientsUpdateClientMutationError = AxiosError<ErrorResponse>;

export const useAdminClientsUpdateClient = <TError = AxiosError<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminClientsUpdateClient>>,
      TError,
      { clientId: string; data: UpdateOAuthClientRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminClientsUpdateClient>>,
  TError,
  { clientId: string; data: UpdateOAuthClientRequest },
  TContext
> => {
  const mutationOptions = getAdminClientsUpdateClientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminClientsDeleteClient = (
  clientId: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  clientId = unref(clientId);

  return axios.delete(`/api/v1/admin/clients/${clientId}`, options);
};

export const getAdminClientsDeleteClientMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminClientsDeleteClient>>,
    TError,
    { clientId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminClientsDeleteClient>>,
  TError,
  { clientId: string },
  TContext
> => {
  const mutationKey = ["adminClientsDeleteClient"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminClientsDeleteClient>>,
    { clientId: string }
  > = (props) => {
    const { clientId } = props ?? {};

    return adminClientsDeleteClient(clientId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminClientsDeleteClientMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminClientsDeleteClient>>
>;

export type AdminClientsDeleteClientMutationError = AxiosError<ErrorResponse>;

export const useAdminClientsDeleteClient = <TError = AxiosError<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminClientsDeleteClient>>,
      TError,
      { clientId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminClientsDeleteClient>>,
  TError,
  { clientId: string },
  TContext
> => {
  const mutationOptions = getAdminClientsDeleteClientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminClientsSetClientStatus = (
  clientId: MaybeRef<string>,
  adminClientsSetClientStatusBody: MaybeRef<AdminClientsSetClientStatusBody>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<OAuthClient>> => {
  clientId = unref(clientId);
  adminClientsSetClientStatusBody = unref(adminClientsSetClientStatusBody);

  return axios.patch(
    `/api/v1/admin/clients/${clientId}/status`,
    adminClientsSetClientStatusBody,
    options,
  );
};

export const getAdminClientsSetClientStatusMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminClientsSetClientStatus>>,
    TError,
    { clientId: string; data: AdminClientsSetClientStatusBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminClientsSetClientStatus>>,
  TError,
  { clientId: string; data: AdminClientsSetClientStatusBody },
  TContext
> => {
  const mutationKey = ["adminClientsSetClientStatus"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminClientsSetClientStatus>>,
    { clientId: string; data: AdminClientsSetClientStatusBody }
  > = (props) => {
    const { clientId, data } = props ?? {};

    return adminClientsSetClientStatus(clientId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminClientsSetClientStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminClientsSetClientStatus>>
>;
export type AdminClientsSetClientStatusMutationBody = AdminClientsSetClientStatusBody;
export type AdminClientsSetClientStatusMutationError = AxiosError<ErrorResponse>;

export const useAdminClientsSetClientStatus = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminClientsSetClientStatus>>,
      TError,
      { clientId: string; data: AdminClientsSetClientStatusBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof adminClientsSetClientStatus>>,
  TError,
  { clientId: string; data: AdminClientsSetClientStatusBody },
  TContext
> => {
  const mutationOptions = getAdminClientsSetClientStatusMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
