/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  ErrorResponse,
  SubscribeTenantApplicationRequest,
  TenantApplication,
  TenantApplicationsListTenantApplications200,
  TenantApplicationsListTenantApplicationsParams,
  UpdateTenantApplicationRequest,
} from "../title.schemas";

export const tenantApplicationsListTenantApplications = (
  tenantId: MaybeRef<string>,
  params?: MaybeRef<TenantApplicationsListTenantApplicationsParams>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantApplicationsListTenantApplications200>> => {
  tenantId = unref(tenantId);
  params = unref(params);

  return axios.get(`/api/v1/tenants/${tenantId}/applications`, {
    ...options,
    params: { ...unref(params), ...options?.params },
  });
};

export const getTenantApplicationsListTenantApplicationsQueryKey = (
  tenantId?: MaybeRef<string>,
  params?: MaybeRef<TenantApplicationsListTenantApplicationsParams>,
) => {
  return ["api", "v1", "tenants", tenantId, "applications", ...(params ? [params] : [])] as const;
};

export const getTenantApplicationsListTenantApplicationsQueryOptions = <
  TData = Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: MaybeRef<string>,
  params?: MaybeRef<TenantApplicationsListTenantApplicationsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getTenantApplicationsListTenantApplicationsQueryKey(tenantId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>
  > = ({ signal }) =>
    tenantApplicationsListTenantApplications(tenantId, params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(tenantId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>,
    TError,
    TData
  >;
};

export type TenantApplicationsListTenantApplicationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>
>;
export type TenantApplicationsListTenantApplicationsQueryError = AxiosError<ErrorResponse>;

export function useTenantApplicationsListTenantApplications<
  TData = Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>,
  TError = AxiosError<ErrorResponse>,
>(
  tenantId: MaybeRef<string>,
  params?: MaybeRef<TenantApplicationsListTenantApplicationsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tenantApplicationsListTenantApplications>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTenantApplicationsListTenantApplicationsQueryOptions(
    tenantId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const tenantApplicationsSubscribeTenantApplication = (
  tenantId: MaybeRef<string>,
  subscribeTenantApplicationRequest: MaybeRef<SubscribeTenantApplicationRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantApplication>> => {
  tenantId = unref(tenantId);
  subscribeTenantApplicationRequest = unref(subscribeTenantApplicationRequest);

  return axios.post(
    `/api/v1/tenants/${tenantId}/applications`,
    subscribeTenantApplicationRequest,
    options,
  );
};

export const getTenantApplicationsSubscribeTenantApplicationMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantApplicationsSubscribeTenantApplication>>,
    TError,
    { tenantId: string; data: SubscribeTenantApplicationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantApplicationsSubscribeTenantApplication>>,
  TError,
  { tenantId: string; data: SubscribeTenantApplicationRequest },
  TContext
> => {
  const mutationKey = ["tenantApplicationsSubscribeTenantApplication"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantApplicationsSubscribeTenantApplication>>,
    { tenantId: string; data: SubscribeTenantApplicationRequest }
  > = (props) => {
    const { tenantId, data } = props ?? {};

    return tenantApplicationsSubscribeTenantApplication(tenantId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantApplicationsSubscribeTenantApplicationMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantApplicationsSubscribeTenantApplication>>
>;
export type TenantApplicationsSubscribeTenantApplicationMutationBody =
  SubscribeTenantApplicationRequest;
export type TenantApplicationsSubscribeTenantApplicationMutationError = AxiosError<ErrorResponse>;

export const useTenantApplicationsSubscribeTenantApplication = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantApplicationsSubscribeTenantApplication>>,
      TError,
      { tenantId: string; data: SubscribeTenantApplicationRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tenantApplicationsSubscribeTenantApplication>>,
  TError,
  { tenantId: string; data: SubscribeTenantApplicationRequest },
  TContext
> => {
  const mutationOptions = getTenantApplicationsSubscribeTenantApplicationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantApplicationsUpdateTenantApplication = (
  tenantId: MaybeRef<string>,
  clientId: MaybeRef<string>,
  updateTenantApplicationRequest: MaybeRef<UpdateTenantApplicationRequest>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TenantApplication>> => {
  tenantId = unref(tenantId);
  clientId = unref(clientId);
  updateTenantApplicationRequest = unref(updateTenantApplicationRequest);

  return axios.patch(
    `/api/v1/tenants/${tenantId}/applications/${clientId}`,
    updateTenantApplicationRequest,
    options,
  );
};

export const getTenantApplicationsUpdateTenantApplicationMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantApplicationsUpdateTenantApplication>>,
    TError,
    { tenantId: string; clientId: string; data: UpdateTenantApplicationRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantApplicationsUpdateTenantApplication>>,
  TError,
  { tenantId: string; clientId: string; data: UpdateTenantApplicationRequest },
  TContext
> => {
  const mutationKey = ["tenantApplicationsUpdateTenantApplication"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantApplicationsUpdateTenantApplication>>,
    { tenantId: string; clientId: string; data: UpdateTenantApplicationRequest }
  > = (props) => {
    const { tenantId, clientId, data } = props ?? {};

    return tenantApplicationsUpdateTenantApplication(tenantId, clientId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantApplicationsUpdateTenantApplicationMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantApplicationsUpdateTenantApplication>>
>;
export type TenantApplicationsUpdateTenantApplicationMutationBody = UpdateTenantApplicationRequest;
export type TenantApplicationsUpdateTenantApplicationMutationError = AxiosError<ErrorResponse>;

export const useTenantApplicationsUpdateTenantApplication = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantApplicationsUpdateTenantApplication>>,
      TError,
      { tenantId: string; clientId: string; data: UpdateTenantApplicationRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tenantApplicationsUpdateTenantApplication>>,
  TError,
  { tenantId: string; clientId: string; data: UpdateTenantApplicationRequest },
  TContext
> => {
  const mutationOptions = getTenantApplicationsUpdateTenantApplicationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const tenantApplicationsRemoveTenantApplication = (
  tenantId: MaybeRef<string>,
  clientId: MaybeRef<string>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  tenantId = unref(tenantId);
  clientId = unref(clientId);

  return axios.delete(`/api/v1/tenants/${tenantId}/applications/${clientId}`, options);
};

export const getTenantApplicationsRemoveTenantApplicationMutationOptions = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tenantApplicationsRemoveTenantApplication>>,
    TError,
    { tenantId: string; clientId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tenantApplicationsRemoveTenantApplication>>,
  TError,
  { tenantId: string; clientId: string },
  TContext
> => {
  const mutationKey = ["tenantApplicationsRemoveTenantApplication"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tenantApplicationsRemoveTenantApplication>>,
    { tenantId: string; clientId: string }
  > = (props) => {
    const { tenantId, clientId } = props ?? {};

    return tenantApplicationsRemoveTenantApplication(tenantId, clientId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TenantApplicationsRemoveTenantApplicationMutationResult = NonNullable<
  Awaited<ReturnType<typeof tenantApplicationsRemoveTenantApplication>>
>;

export type TenantApplicationsRemoveTenantApplicationMutationError = AxiosError<ErrorResponse>;

export const useTenantApplicationsRemoveTenantApplication = <
  TError = AxiosError<ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tenantApplicationsRemoveTenantApplication>>,
      TError,
      { tenantId: string; clientId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof tenantApplicationsRemoveTenantApplication>>,
  TError,
  { tenantId: string; clientId: string },
  TContext
> => {
  const mutationOptions = getTenantApplicationsRemoveTenantApplicationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
