/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
export interface ApiKey {
  id: string;
  tenantId: string;
  /**
   * @minLength 2
   * @maxLength 128
   */
  name: string;
  /**
   * @minLength 8
   * @maxLength 16
   */
  prefix: string;
  status: ApiKeyStatus;
  scopes: string[];
  createdAt: string;
  lastUsedAt?: string;
  expiresAt?: string;
  revokedAt?: string;
}

export type ApiKeyStatus = typeof ApiKeyStatus[keyof typeof ApiKeyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiKeyStatus = {
  active: 'active',
  revoked: 'revoked',
  expired: 'expired',
} as const;

export interface App {
  id: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  description?: string;
  icon?: string;
  sortOrder: number;
  status: AppStatus;
  /**
   * @minLength 2
   * @maxLength 128
   */
  clientId: string;
  clientSecret?: string;
  redirectUris: string[];
  scopes: string[];
  grantTypes: OAuthGrantType[];
  isFirstParty: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AppPublicInfo {
  id: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  description?: string;
  icon?: string;
  status: AppStatus;
}

export type AppStatus = typeof AppStatus[keyof typeof AppStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

export type AuditAction = typeof AuditAction[keyof typeof AuditAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditAction = {
  user_created: 'user_created',
  user_updated: 'user_updated',
  user_deleted: 'user_deleted',
  role_assigned: 'role_assigned',
  role_revoked: 'role_revoked',
  login_success: 'login_success',
  login_failed: 'login_failed',
  oauth_token_issued: 'oauth_token_issued',
  api_key_created: 'api_key_created',
  api_key_revoked: 'api_key_revoked',
} as const;

export type AuditEventMetadata = {[key: string]: unknown};

export interface AuditEvent {
  id: string;
  tenantId: string;
  actorUserId?: string;
  action: AuditAction;
  targetUserId?: string;
  metadata?: AuditEventMetadata;
  occurredAt: string;
}

export type AuthorizeCodeRequestResponseType = typeof AuthorizeCodeRequestResponseType[keyof typeof AuthorizeCodeRequestResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthorizeCodeRequestResponseType = {
  code: 'code',
} as const;

export interface AuthorizeCodeRequest {
  clientId: string;
  /**
   * @minLength 1
   * @maxLength 2048
   */
  redirectUri: string;
  responseType: AuthorizeCodeRequestResponseType;
  scope: string;
  state: string;
  tenantId: string;
}

export interface CreateApiKeyRequest {
  /**
   * @minLength 2
   * @maxLength 128
   */
  name: string;
  scopes?: string[];
  expiresAt?: string;
}

export interface CreateApiKeyResponse {
  apiKey: ApiKey;
  /**
   * @minLength 16
   * @maxLength 256
   */
  secret: string;
}

export interface CreateAppRequest {
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  description?: string;
  icon?: string;
  sortOrder?: number;
  status?: AppStatus;
  /**
   * @minLength 2
   * @maxLength 128
   */
  clientId: string;
  clientSecret?: string;
  redirectUris: string[];
  scopes?: string[];
  grantTypes?: OAuthGrantType[];
  isFirstParty?: boolean;
}

export interface CreateMenuRequest {
  parentId?: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  path?: string;
  icon?: string;
  type?: MenuType;
  sortOrder?: number;
  status?: MenuStatus;
}

export interface CreateRoleRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: string;
  permissionIds?: string[];
}

export interface CreateTenantRequest {
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  settings?: TenantSettings;
}

export interface CreateUserRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  email: string;
  displayName?: string;
  password: string;
  roleIds?: string[];
}

export interface CurrentUser {
  id: string;
  email: string;
  displayName?: string;
  memberships: TenantMembership[];
  currentTenantId?: string;
}

export interface EffectiveMenuNode {
  id: string;
  appId: string;
  parentId?: string;
  code: string;
  name: string;
  path?: string;
  icon?: string;
  type: MenuType;
  sortOrder: number;
  children: EffectiveMenuNode[];
}

export type ErrorResponseDetails = {[key: string]: unknown};

export interface ErrorResponse {
  code: string;
  message: string;
  details?: ErrorResponseDetails;
}

export interface LoginRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  password: string;
  tenantCode?: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
  userId: string;
  currentTenantId: string;
}

export type MembershipStatus = typeof MembershipStatus[keyof typeof MembershipStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MembershipStatus = {
  active: 'active',
  invited: 'invited',
  removed: 'removed',
} as const;

export interface Menu {
  id: string;
  appId: string;
  parentId?: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  path?: string;
  icon?: string;
  type: MenuType;
  sortOrder: number;
  status: MenuStatus;
  createdAt: string;
  updatedAt: string;
}

export type MenuStatus = typeof MenuStatus[keyof typeof MenuStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MenuStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;

export type MenuType = typeof MenuType[keyof typeof MenuType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MenuType = {
  group: 'group',
  page: 'page',
  action: 'action',
} as const;

export type OAuthGrantType = typeof OAuthGrantType[keyof typeof OAuthGrantType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OAuthGrantType = {
  authorization_code: 'authorization_code',
  refresh_token: 'refresh_token',
  client_credentials: 'client_credentials',
  password: 'password',
} as const;

export interface OidcCallbackRequest {
  code: string;
  state: string;
  clientId: string;
}

export interface ReorderMenuRequest {
  orderedMenuIds: string[];
}

export interface Role {
  id: string;
  tenantId: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  description?: string;
  permissionIds: string[];
  createdAt: string;
  updatedAt: string;
}

export interface RoleMenuGrant {
  roleId: string;
  tenantId: string;
  menuIds: string[];
  updatedAt: string;
}

export interface SetRoleMenusRequest {
  menuIds: string[];
}

export interface SwitchTenantResponse {
  accessToken: string;
  refreshToken?: string;
  expiresAt: string;
  tenantId: string;
}

export interface Tenant {
  id: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  code: string;
  /**
   * @minLength 2
   * @maxLength 255
   */
  name: string;
  status: TenantStatus;
  settings?: TenantSettings;
  createdAt: string;
  updatedAt: string;
}

export interface TenantMembership {
  id: string;
  userId: string;
  tenantId: string;
  roleIds: string[];
  status: MembershipStatus;
  joinedAt: string;
}

export interface TenantSettings {
  themeColor?: string;
  locale?: string;
  maxUsers?: number;
}

export type TenantStatus = typeof TenantStatus[keyof typeof TenantStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantStatus = {
  active: 'active',
  suspended: 'suspended',
  archived: 'archived',
} as const;

export type TokenRequestGrantType = typeof TokenRequestGrantType[keyof typeof TokenRequestGrantType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenRequestGrantType = {
  authorization_code: 'authorization_code',
  refresh_token: 'refresh_token',
} as const;

export interface TokenRequest {
  grantType: TokenRequestGrantType;
  code?: string;
  refreshToken?: string;
  clientId: string;
  clientSecret?: string;
  tenantId: string;
  redirectUri?: string;
}

export interface TokenResponse {
  accessToken: string;
  refreshToken?: string;
  tokenType: string;
  expiresIn: number;
  scope: string;
}

export interface UpdateAppRequest {
  name?: string;
  description?: string;
  icon?: string;
  sortOrder?: number;
  status?: AppStatus;
  redirectUris?: string[];
  scopes?: string[];
  grantTypes?: OAuthGrantType[];
  isFirstParty?: boolean;
}

export interface UpdateMenuRequest {
  parentId?: string;
  name?: string;
  path?: string;
  icon?: string;
  type?: MenuType;
  sortOrder?: number;
  status?: MenuStatus;
}

export interface UpdateRoleRequest {
  name?: string;
  description?: string;
  permissionIds?: string[];
}

export interface UpdateTenantRequest {
  name?: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  code?: string;
  status?: TenantStatus;
  settings?: TenantSettings;
}

export interface UpdateUserRequest {
  displayName?: string;
  email?: string;
  status?: UserStatus;
  roleIds?: string[];
}

export interface User {
  id: string;
  tenantId: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  email: string;
  displayName?: string;
  status: UserStatus;
  roleIds: string[];
  createdAt: string;
  updatedAt: string;
}

export type UserStatus = typeof UserStatus[keyof typeof UserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserStatus = {
  active: 'active',
  invited: 'invited',
  suspended: 'suspended',
  disabled: 'disabled',
} as const;

export type AdminAppsListAppsParams = {
page?: number;
pageSize?: number;
};

export type AdminAppsListApps200 = {
  items: App[];
  page: number;
  pageSize: number;
  total: number;
};

export type AdminAppMenusMoveMenuBody = {
  parentId?: string;
};

export type AdminAppsSetAppStatusBody = {
  status: AppStatus;
};

export type AdminTenantsListTenantsParams = {
page?: number;
pageSize?: number;
};

export type AdminTenantsListTenants200 = {
  items: Tenant[];
  page: number;
  pageSize: number;
  total: number;
};

export type MeGetMyMenus200 = {[key: string]: EffectiveMenuNode[]};

export type OAuthAuthorize200 = {
  code: string;
  state: string;
};

export type TenantApiKeysListApiKeysParams = {
page?: number;
pageSize?: number;
};

export type TenantApiKeysListApiKeys200 = {
  items: ApiKey[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantAuditListAuditEventsParams = {
page?: number;
pageSize?: number;
actorUserId?: string;
action?: AuditAction;
from?: string;
to?: string;
};

export type TenantAuditListAuditEvents200 = {
  items: AuditEvent[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantAuditListAuditEventsByUserParams = {
page?: number;
pageSize?: number;
};

export type TenantAuditListAuditEventsByUser200 = {
  items: AuditEvent[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantAuditExportAuditEventsBodyFormat = typeof TenantAuditExportAuditEventsBodyFormat[keyof typeof TenantAuditExportAuditEventsBodyFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantAuditExportAuditEventsBodyFormat = {
  csv: 'csv',
  json: 'json',
} as const;

export type TenantAuditExportAuditEventsBody = {
  from: string;
  to: string;
  format: TenantAuditExportAuditEventsBodyFormat;
};

export type TenantAuditExportAuditEvents200 = {
  downloadUrl: string;
};

export type TenantAuditGetRetentionPolicy200 = {
  retentionDays: number;
};

export type TenantAuditSetRetentionPolicyBody = {
  retentionDays: number;
};

export type TenantAuditSetRetentionPolicy200 = {
  retentionDays: number;
};

export type TenantRolesListRolesParams = {
page?: number;
pageSize?: number;
};

export type TenantRolesListRoles200 = {
  items: Role[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantRolesSetPermissionsBody = {
  permissionIds: string[];
};

export type TenantUsersListUsersParams = {
page?: number;
pageSize?: number;
status?: UserStatus;
};

export type TenantUsersListUsers200 = {
  items: User[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantUsersInviteUserBody = {
  email: string;
  roleIds?: string[];
};

export type TenantUsersAssignRolesBody = {
  roleIds: string[];
};

export type TenantUsersChangeUserStatusBody = {
  status: UserStatus;
};

