/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * (title)
 * OpenAPI spec version: 0.0.0
 */
export type AuthorizeCodeRequestResponseType = typeof AuthorizeCodeRequestResponseType[keyof typeof AuthorizeCodeRequestResponseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthorizeCodeRequestResponseType = {
  code: 'code',
} as const;

export interface AuthorizeCodeRequest {
  clientId: string;
  /**
   * @minLength 1
   * @maxLength 500
   */
  redirectUri: string;
  responseType: AuthorizeCodeRequestResponseType;
  scope?: string;
  state: string;
}

export interface CreateOAuthClientRequest {
  clientId: string;
  clientName: string;
  clientSecret: string;
  grantTypes: string;
  redirectUris: string;
  scopes?: string;
  accessTokenValidity?: number;
  refreshTokenValidity?: number;
  autoApprove?: boolean;
}

export interface CreateSysMenuRequest {
  parentId?: string;
  title: string;
  type: SysMenuType;
  path?: string;
  component?: string;
  perms?: string;
  icon?: string;
  sortOrder?: number;
}

export interface CreateSysRoleRequest {
  clientId: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  roleCode: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  roleName: string;
  description?: string;
  isPreset?: boolean;
}

export interface CreateSysUserRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  password: string;
  email?: string;
  mobile?: string;
}

export interface CreateTenantRequest {
  /**
   * @minLength 2
   * @maxLength 64
   */
  tenantKey: string;
  /**
   * @minLength 2
   * @maxLength 128
   */
  name: string;
}

export interface CurrentUser {
  id: string;
  email?: string;
  memberships: TenantMembership[];
  currentTenantId?: string;
}

export interface EffectiveMenuNode {
  id: string;
  clientId: string;
  parentId: string;
  title: string;
  type: SysMenuType;
  path?: string;
  component?: string;
  perms?: string;
  icon?: string;
  sortOrder: number;
  children: EffectiveMenuNode[];
}

export type ErrorResponseDetails = {[key: string]: unknown};

export interface ErrorResponse {
  code: string;
  message: string;
  details?: ErrorResponseDetails;
}

export interface LockedAccountResponse {
  code: string;
  message: string;
  lockedUntil: string;
  remainingAttempts?: number;
}

export interface LoginRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  password: string;
  clientId: string;
}

export interface LoginResponse {
  user: SysUser;
  availableTenants: TenantMembership[];
  userId: string;
  currentTenantId?: string;
  accessToken?: string;
  refreshToken?: string;
  tokenType?: string;
  expiresIn?: number;
  clientId: string;
}

export interface OAuthClient {
  id: string;
  clientId: string;
  clientName: string;
  grantTypes: string;
  redirectUris: string;
  scopes?: string;
  accessTokenValidity: number;
  refreshTokenValidity: number;
  autoApprove: boolean;
  status: number;
  createdAt: string;
  updatedAt: string;
}

export interface OAuthClientPublicInfo {
  clientId: string;
  clientName: string;
  status: number;
}

export interface ReorderSysMenuRequest {
  orderedMenuIds: string[];
}

export interface RoleMenuGrant {
  roleId: string;
  tenantId: string;
  menuIds: string[];
  updatedAt: string;
}

export interface SetSysRoleMenusRequest {
  menuIds: string[];
}

export interface SetTenantMemberRolesRequest {
  roleIds: string[];
}

export interface SubscribeTenantApplicationRequest {
  clientId: string;
  expireTime?: string;
}

export interface SwitchTenantResponse {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
  tenantId: string;
}

export interface SysMenu {
  id: string;
  clientId: string;
  parentId: string;
  title: string;
  type: SysMenuType;
  path?: string;
  component?: string;
  perms?: string;
  icon?: string;
  sortOrder: number;
  status: number;
  createdAt: string;
}

export type SysMenuType = typeof SysMenuType[keyof typeof SysMenuType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SysMenuType = {
  directory: 'directory',
  menu: 'menu',
  button: 'button',
} as const;

export interface SysRole {
  id: string;
  tenantId: string;
  clientId: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  roleCode: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  roleName: string;
  description?: string;
  isPreset: boolean;
  status: number;
  createdAt: string;
  updatedAt: string;
}

export interface SysUser {
  id: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  email?: string;
  mobile?: string;
  status: SysUserStatus;
  failedAttempts?: number;
  lockedUntil?: string;
  createdAt: string;
  updatedAt: string;
}

export type SysUserStatus = typeof SysUserStatus[keyof typeof SysUserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SysUserStatus = {
  active: 'active',
  invited: 'invited',
  disabled: 'disabled',
} as const;

export interface Tenant {
  id: string;
  /**
   * @minLength 2
   * @maxLength 64
   */
  tenantKey: string;
  /**
   * @minLength 2
   * @maxLength 128
   */
  name: string;
  status: TenantStatus;
  createdAt: string;
  updatedAt: string;
}

export interface TenantApplication {
  id: string;
  tenantId: string;
  clientId: string;
  status: number;
  expireTime?: string;
  createdAt: string;
}

export interface TenantMember {
  id: string;
  tenantId: string;
  userId: string;
  memberName?: string;
  isOwner: boolean;
  status: TenantMemberStatus;
  createdAt: string;
  updatedAt: string;
}

export type TenantMemberStatus = typeof TenantMemberStatus[keyof typeof TenantMemberStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantMemberStatus = {
  active: 'active',
  invited: 'invited',
  suspended: 'suspended',
  disabled: 'disabled',
} as const;

export interface TenantMemberUserView {
  id: string;
  tenantId: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  email?: string;
  status: TenantMemberStatus;
  roleIds: string[];
  createdAt: string;
  updatedAt: string;
}

export interface TenantMemberView {
  member: TenantMember;
  user: SysUser;
  roles: string[];
}

export interface TenantMembership {
  id: string;
  userId: string;
  tenantId: string;
  roleIds: string[];
  status: TenantMemberStatus;
  joinedAt: string;
}

export type TenantStatus = typeof TenantStatus[keyof typeof TenantStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantStatus = {
  active: 'active',
  suspended: 'suspended',
} as const;

export type TokenRequestGrantType = typeof TokenRequestGrantType[keyof typeof TokenRequestGrantType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TokenRequestGrantType = {
  authorization_code: 'authorization_code',
  refresh_token: 'refresh_token',
} as const;

export interface TokenRequest {
  grantType: TokenRequestGrantType;
  code?: string;
  refreshToken?: string;
  clientId: string;
  clientSecret?: string;
  redirectUri?: string;
}

export interface TokenResponse {
  accessToken: string;
  refreshToken: string;
  tokenType: string;
  expiresIn: number;
  scope?: string;
  userId: string;
  clientId: string;
  tenantId: string;
}

export interface UpdateOAuthClientRequest {
  clientName?: string;
  grantTypes?: string;
  redirectUris?: string;
  scopes?: string;
  accessTokenValidity?: number;
  refreshTokenValidity?: number;
  autoApprove?: boolean;
  status?: number;
}

export interface UpdateSysMenuRequest {
  parentId?: string;
  title?: string;
  type?: SysMenuType;
  path?: string;
  component?: string;
  perms?: string;
  icon?: string;
  sortOrder?: number;
  status?: number;
}

export interface UpdateSysRoleRequest {
  /**
   * @minLength 1
   * @maxLength 64
   */
  roleName?: string;
  description?: string;
  status?: number;
}

export interface UpdateSysUserRequest {
  email?: string;
  mobile?: string;
  status?: SysUserStatus;
}

export interface UpdateTenantApplicationRequest {
  status: number;
  expireTime?: string;
}

export interface UpdateTenantRequest {
  /**
   * @minLength 2
   * @maxLength 128
   */
  name?: string;
  status?: TenantStatus;
}

export type AdminClientsListClientsParams = {
page?: number;
pageSize?: number;
};

export type AdminClientsListClients200 = {
  items: OAuthClient[];
  page: number;
  pageSize: number;
  total: number;
};

export type AdminClientsSetClientStatusBody = {
  status: number;
};

export type AdminTenantsListTenantsParams = {
page?: number;
pageSize?: number;
};

export type AdminTenantsListTenants200 = {
  items: Tenant[];
  page: number;
  pageSize: number;
  total: number;
};

export type SessionsLoginDefault = LockedAccountResponse | ErrorResponse;

export type ClientMenusMoveSysMenuBody = {
  parentId?: string;
};

export type MeGetMyMenusParams = {
clientId?: string;
};

export type MeGetMyMenus200 = {[key: string]: EffectiveMenuNode[]};

export type MeListMyTenantsParams = {
clientId?: string;
};

export type MeSwitchTenantParams = {
clientId?: string;
};

export type OAuthAuthorize200 = {
  code: string;
  state: string;
};

export type TenantApplicationsListTenantApplicationsParams = {
page?: number;
pageSize?: number;
};

export type TenantApplicationsListTenantApplications200 = {
  items: TenantApplication[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantMembersListTenantUsersParams = {
page?: number;
pageSize?: number;
status?: TenantMemberStatus;
};

export type TenantMembersListTenantUsers200 = {
  items: TenantMemberUserView[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantMembersInviteTenantUserBody = {
  email?: string;
  mobile?: string;
};

export type TenantMembersChangeTenantUserStatusBody = {
  status: TenantMemberStatus;
};

export type TenantRolesListSysRolesParams = {
clientId?: string;
page?: number;
pageSize?: number;
};

export type TenantRolesListSysRoles200 = {
  items: SysRole[];
  page: number;
  pageSize: number;
  total: number;
};

export type TenantRoleMenusListSysRoleMenusParams = {
clientId?: string;
};

export type TenantRoleMenusSetSysRoleMenusParams = {
clientId?: string;
};

export type TenantRoleMenusClearSysRoleMenusParams = {
clientId?: string;
};

